name:                aoc21
version:             0.1.0.0
github:              "sebastianselander/aoc21"
license:             BSD3
author:              "Sebastian Selander"
maintainer:          "sebastian.selander@gmail.com"
copyright:           "2021 Sebastian Selander"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: The premier haskell solutions for advent of code 2021

dependencies:
- base >= 4.7 && < 5
- containers
- text
- time
- extra
- directory

library:
  source-dirs: src
  # exposed-dirs:
  #   - Misc
  #   - Days.Day1
  #   - Days.Day2
  #   - Days.Day3
  #   - Days.Day4
  #   - Days.Day5
  #   - Days.Day6
  #   - Days.Day7
  #   - Days.Day8
  #   - Days.Day9
  #   - Days.Day10
  #   - Days.Day11
  #   - Days.Day12
  #   - Days.Day13
  #   - Days.Day14
  #   - Days.Day15
  #   - Days.Day16
  #   - Days.Day17
  #   - Days.Day18
  #   - Days.Day19
  #   - Days.Day20
  #   - Days.Day21
  #   - Days.Day22
  #   - Days.Day23
  #   - Days.Day24
  #   - Days.Day25

executables:
  aoc21-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc21

tests:
  aoc21-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc21

default-extensions:
  - ImportQualifiedPost
  - TupleSections
  - LambdaCase
  - OverloadedLists
  - OverloadedStrings

