name:                aoc21
version:             0.1.0.0
github:              "sebastianselander/aoc21"
license:             BSD3
author:              "Sebastian Selander"
maintainer:          "sebastian.selander@gmail.com"
copyright:           "2021 Sebastian Selander"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: The premier haskell solutions for advent of code 2021

dependencies:
- base >= 4.7 && < 5
- containers
- text

library:
  source-dirs: src
  exposed-dirs:
    -  Day1

executables:
  aoc21-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc21

tests:
  aoc21-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc21

default-extensions:
  - ImportQualifiedPost
  - LambdaCase
  - OverloadedLists
  - OverloadedStrings

